### ISSUE TITLE
Config errors

### ISSUE THREAD

**Issue by akavi1** [Arthur-Milchior/Quick_Tagging#11]
Removing the q and w shortcuts in config makes the addon report a popup saying there is a shortcut conflict, even though there isn't. Removing these two lines entirely prevents Anki from opening.
"add tag shortcut": "q",
"edit tag shortcut": "w",

**Comment by Zoomaaa** [comment]
I faced the same problem but found the solution, so for people with the same problem, just bind those shortcuts to unused keys like F21 or something like that
